name: 2. Enrich Anime Details

on:
  workflow_dispatch: # Jalankan manual untuk melanjutkan
  schedule:
    - cron: '0 0 * * 0' # Jalankan otomatis setiap hari Minggu

jobs:
  enrich:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run detail enrichment script
        timeout-minutes: 350
        run: python 2_enrich_details.py
      
      - name: Commit and push details
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add anime_details.json
          git diff --staged --quiet || (git commit -m "Update anime details" && git push)
